### ISSUE TITLE
"Remember me" checkbox not remembering browser in Devise 2.0.0

### ISSUE THREAD

**Issue by pkarjala** [wmlele/devise-otp#148]
When signing into a 2FA session and checking the "Remember me for 7 days" option, the value generated is not 7 days.

The `otp_challenge_expires` option generated has an extremely close timestamp to the `updated_at` value of the record.

Example:

`updated_at = 2026-06-24 17:51:33.831532`
`otp_challenge_expires = 2026-06-24 17:52:42.159838`

Instead, the `otp_challenge_expires` value should be 7 days later as per the "Remember me" checkbox.

Applicable info:

Ruby 3.2.2
Rails 7.2.3.1
Devise 4.9.4
devise-otp 2.0.0

**Comment by pkarjala** [comment]
Any updates on potential fixes for this?  The system that I have which is still on Rails 7.1.x which is EOL does not exhibit this behavior.

I also verified that the configuration in the settings file is as follows:

```
 # The user is allowed to set his browser as "trusted", no more OTP challenges will be
 # asked for that browser, for a limited time.
 # set to false to disable setting the browser as trusted
 config.otp_trust_persistence = 1.week
```

**Comment by pkarjala** [comment]
This issue should not be marked as completed, I accidentally clicked on that.  Can a team member please re-open?

**Comment by pkarjala** [comment]
Also of note, I get the following error when trying to view the `otp/token` path to edit a user's token, it gives the following error:

```
NoMethodError in DeviseOtp::Devise::OtpTokens#show 

Showing /path/to/rails/applicatiaon/app/views/devise/otp_tokens/_trusted_devices.html.erb where line #13 raised:

undefined method `persistence_otp_token_path_for' for #<ActionView::Base:0x0000000001d678>

Extracted source (around line #13): 

  <% else %>
      <p class="alert alert-secondary"><strong>Status: </strong><%= I18n.t('browser_not_trusted', scope: 'devise.otp.trusted_browsers') %></p>
      <p><%= link_to I18n.t('trust_add', scope: 'devise.otp.trusted_browsers'), persistence_otp_token_path_for(resource_name), class: "btn btn-primary" %></p>
    <% end %>

    <p><%= button_to I18n.t('trust_clear', scope: 'devise.otp.trusted_browsers'), persistence_otp_token_path_for(resource_name), method: :delete, class: "btn btn-danger" %></p>

```

**Comment by pkarjala** [comment]
Spent some time today doing some regression testing.  From what I can tell, the "Remember me" option works fine in `devise-otp` 0.8.0, 1.00, and 1.1.0.

The issue appears to occur as soon as I bump to 2.0.0.

So something may have been introduced in the codebase that broke this functionality during that time.

Also of note, checking the logs for the login flow, I can see that there is an appended `&remember_me=false` in the GET call for the `/otp/credentials?challenge=[challenge key]&remember_me=false` when reaching the "Check Token" route that was not present in the < 2.0.0 releases.

**Comment by strouptl** [comment]
Hi @pkarjala,

Thank you for your work on this issue, and I apologize for the delay. After reviewing the Github issue, I believe the code is working as intended.

Please let me know if you see otherwise (particularly, if you are noticing actual issues in the browser). Here are the answers to your questions, though, in the mean time:

1. The otp_challenge_expires column
The otp_challenge_expires column is actually unrelated to the "Remember me" feature. Rather than specifying the validity of the user's session, it specifies how long the user has to enter a correct OTP token after entering their password, and is configured via the otp_authentication_timeout value (defaults to 3 minutes).

This is important, as the user is not actually authenticated until they complete the OTP form, being retrieved by the OTP credentials form via the freshly generated otp_session_challenge token. And since the otp_session_challenge is public (passed via the URL), it depends on security via obscurity, requiring a shortened window for the user to complete (e.g. 3 minutes).

Reference. https://github.com/wmlele/devise-otp/blob/fcd696dd414e42db13d1526935b61ec7fda553c0/lib/devise_otp_authenticatable/models/otp_authenticatable.rb#L81-L85

2. The persistence_otp_token_path_for helper
This was the name of the paths for the Trusted Browser functionality in version 1.0.0. However, it was too confusing, as it utilized the GET, POST, and DELETE actions for the same path to perform unrelated features (trusting, untrusting, and clearing all browsers). As a result, we renamed these a bit in 2.0.0, distinguishing between user_otp_persistence_path, with POST and DELETE actions for controlling the single brower, and a separate reset_user_otp_persistence_path, with a single DELETE action for clearing all trusted browsers.

References:
- https://github.com/wmlele/devise-otp/blob/fcd696dd414e42db13d1526935b61ec7fda553c0/lib/devise_otp_authenticatable/routes.rb#L13-L18
- https://github.com/wmlele/devise-otp/blob/fcd696dd414e42db13d1526935b61ec7fda553c0/lib/devise_otp_authenticatable/controllers/url_helpers.rb#L14-L22

3. Regarding the Trusted Browser functionality, I realized that we didn't have any tests to confirm that the sign in process honors the Trusted Browser setting, so I am adding this just to make sure.

**Comment by strouptl** [comment]
Regarding the challenge key and the remember_me token, we had to make a lot of changes to the authentication flow for security reasons in v1.0.0 (updating the Warden strategy to redirect the user via the challenge token you noted rather than logging them in immediately), and then we updated the flow to preserve the user's "Remember Me" selection until the OTP credentials page in v2.0.0. I would refer you to the CHANGELOG, as well as the integratoin tests for further detail.

All that said, devise-otp is quite complicated, so thank you again for your sharp eye, and please keep the questions coming!

**Comment by strouptl** [comment]
One last note: I would like to review the database columns to make sure there are no unused columns from pre-1.0.0, and I think there may be a couple of other holdovers from pre-1.0.0 in the tests (e.g. the otp_mandatory? class method in test/dummy/app/models/admin.rb). I would welcome your help if you have further interest/time!

**Comment by pkarjala** [comment]
Thank you for the review and thorough explanations; I'll go back and try to do some additional testing on a fresh install to see if I can duplicate the issue I'm seeing with devise-otp 2.0.0 and it not honoring the "Remember me" checkbox on our current install.

Regarding database columns and other test review, I can open a separate issue to track discussion and assistance with that so as to not muddle the discussion on this one.

**Comment by strouptl** [comment]
Sounds good!
